name: billsplit

services:
  - name: billsplit
    image:
      repository: 740994137039.dkr.ecr.eu-west-1.amazonaws.com/apps/billsplit
      tag: cf4b4a9f0422cdff65c0b8d6b0079f956a18cc77
    resources:
      cpu: "100m"
      memory: "128Mi"
    command: ["/usr/local/bin/billsplit"]
    iamRoleARN: "arn:aws:iam::740994137039:role/k8s-mgmt-billsplit"
    env:
      - name: S3_BUCKET
        rawValue: "fergalhk-billsplit-live"
    ingress:
      port: 8080
      public:
        domain: billsplit.fergal.website

initJobs:
  - name: seed
    image:
      repository: 740994137039.dkr.ecr.eu-west-1.amazonaws.com/apps/billsplit
      tag: cf4b4a9f0422cdff65c0b8d6b0079f956a18cc77
    resources:
      cpu: "100m"
      memory: "128Mi"
    command: ["/usr/local/bin/seed"]
    args: ["-initial"]
    iamRoleARN: "arn:aws:iam::740994137039:role/k8s-mgmt-billsplit"
    env:
      - name: S3_BUCKET
        rawValue: "fergalhk-billsplit-live"

cronJobs:
  - name: fxrates-sync
    image:
      repository: 740994137039.dkr.ecr.eu-west-1.amazonaws.com/apps/billsplit
      tag: cf4b4a9f0422cdff65c0b8d6b0079f956a18cc77
    resources:
      cpu: "100m"
      memory: "128Mi"
    command: ["/usr/local/bin/fxrates-sync"]
    iamRoleARN: "arn:aws:iam::740994137039:role/k8s-mgmt-billsplit"
    env:
      - name: S3_BUCKET
        rawValue: "fergalhk-billsplit-live"
    schedule: "0 0 * * *"
