common:
  ecr:
    pushIAMRoleARN: arn:aws:iam::740994137039:role/gh-ecr-fergalhk-lab-apps
    region: eu-west-1
    imagePrefix: 740994137039.dkr.ecr.eu-west-1.amazonaws.com/apps

apps:
  - name: billsplit
    path: billsplit/
    tests:
      - name: go
        run: go test -v ./billsplit/...
      - name: frontend
        run: npm --prefix billsplit/frontend ci && npm --prefix billsplit/frontend test
  - name: capi-argocd-bootstrapper
    path: capi-argocd-bootstrapper/
    image: 740994137039.dkr.ecr.eu-west-1.amazonaws.com/capi-argocd-bootstrapper
    setupCommands:
      - go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.23.3
    tests:
      - name: go
        run: KUBEBUILDER_ASSETS="$(setup-envtest use 1.35.0 -p path)" go test -v ./capi-argocd-bootstrapper/...
